/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spedd_click_pin_taconet;

/**
 *
 * @author Donatien
 */
public class fenetreDeJeu extends javax.swing.JFrame {

    /**
     * Creates new form fenetreDeJeu
     */
    public fenetreDeJeu() {
        initComponents();
        Panel_intro.setVisible(false);
        Panel_jeu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_intro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_start = new javax.swing.JButton();
        Panel_jeu = new javax.swing.JPanel();
        Panel_grille = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_score = new javax.swing.JLabel();
        Panel_fin = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_intro.setBackground(new java.awt.Color(0, 0, 153));
        Panel_intro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Terminator Two", 3, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("SPEED CLICK");
        Panel_intro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 620, 320));

        btn_start.setBackground(new java.awt.Color(255, 255, 255));
        btn_start.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        btn_start.setText("Start");
        Panel_intro.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 170, 90));

        getContentPane().add(Panel_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 920, 580));

        Panel_jeu.setBackground(new java.awt.Color(204, 153, 255));
        Panel_jeu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_grille.setBackground(new java.awt.Color(255, 255, 255));
        Panel_grille.setLayout(new java.awt.GridLayout(7, 7));
        Panel_jeu.add(Panel_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 672, 672));

        jLabel2.setFont(new java.awt.Font("Terminator Two", 3, 24)); // NOI18N
        jLabel2.setText("SPEED CLICK");
        Panel_jeu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 200, 50));

        jLabel3.setFont(new java.awt.Font("Terminator Two", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Score:");
        Panel_jeu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 90, 70));

        lbl_score.setFont(new java.awt.Font("Terminator Two", 1, 18)); // NOI18N
        lbl_score.setForeground(new java.awt.Color(255, 255, 255));
        lbl_score.setText("arbitraire");
        Panel_jeu.add(lbl_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 270, -1, -1));

        getContentPane().add(Panel_jeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 940, 620));

        Panel_fin.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout Panel_finLayout = new javax.swing.GroupLayout(Panel_fin);
        Panel_fin.setLayout(Panel_finLayout);
        Panel_finLayout.setHorizontalGroup(
            Panel_finLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        Panel_finLayout.setVerticalGroup(
            Panel_finLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 690));

        setBounds(0, 0, 1046, 729);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetreDeJeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_fin;
    private javax.swing.JPanel Panel_grille;
    private javax.swing.JPanel Panel_intro;
    private javax.swing.JPanel Panel_jeu;
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_score;
    // End of variables declaration//GEN-END:variables
}
